//** This file was NOT generated by SquareLine Studio **
// Make sure "Call functions export file" option is set to "dont't export" else this will be overwritten

#include "ui.h"

void button_pressed(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *btn = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED)
    {
        static uint8_t count = 0;
        count++;

        /*Get the first child of the button which is the label and change its text*/
        lv_obj_t *label = lv_obj_get_child(btn, 0);
        lv_label_set_text_fmt(label, "Button Pressed: %d", count);
    }
}